services:
    neo4j:
        image: neo4j:latest
        ports:
            - 7474:7474
            - 7687:7687
        volumes:
            - ./db/data:/data
            - ./db/logs:/logs
            - ./import:/var/lib/neo4j/import
            - ./db/plugins:/plugins

        ## first time setup
        # environment:
        #     - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
        #     - NEO4JLABS_PLUGINS=["graph-data-science", "apoc"]
