services:
    neo4j:
        image: neo4j:latest
        ports:
            - 7474:7474
            - 7687:7687
        volumes:
            - neo4j-db:/data
            - ./db/logs:/logs
            - ./db/plugins:/plugins
            - ./db/import:/var/lib/neo4j/import

        # first time setup
        environment:
            - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
            - NEO4J_PLUGINS=["graph-data-science", "apoc"]

volumes:
    neo4j-db:
